USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS COUNTRY_ML;
USE DATABASE COUNTRY_ML;
CREATE SCHEMA IF NOT EXISTS ACTUARIAL_PRICING;
USE SCHEMA ACTUARIAL_PRICING;
CREATE STAGE IF NOT EXISTS DATA_STAGE;
CREATE STAGE IF NOT EXISTS OUTPUT_STAGE;
CREATE STAGE IF NOT EXISTS PAYLOAD_STAGE;

COPY FILES INTO @DATA_STAGE
FROM 'snow://workspace/USER$.PUBLIC."demo-actuarial-ml"/versions/live/'
FILES=('data/policy_freq.xml', 'data/policy_sev.xml');
